### ISSUE TITLE
how are you removing whitespace?

### ISSUE THREAD

**Issue by theshaune** [dburles/inline-block-test#1]
how are you removing whitespace?

**Comment by dburles** [comment]
i found a way that works if we're using an `{{#each}}` block

condense it like:
`{{#each something}}{{> item}}{{/each}}`

not great though

**Comment by theshaune** [comment]
yeah, not nice, but does work, also a good method is using:
< u l>
   < li >
     content
  < li >
     content

ommit the closing tag and it won't create the whitespace

**Comment by dburles** [comment]
haha that's so hack
